---
title: "Activity First post"
date: "2024-11-06"
---

## Stating and Explaining the Title of my Senior Comp Project

Title: CaddySense: AI-Powered Golf Performance Assistant

The title of my project if CaddySense: AI-Powered Golf Performance Assistant. This name combines two main ideas, a caddy, which represents personalized on course guidance, and sense, which represents intelligence and insight driven by local AI and data analysis.

CaddySense is currently a python based system that is both using local data storage, visualization, and a natural language processor in order to deliver intelligent insights for golfers. It also has a built in AI assistant that helps players understand which exact parts of their game most affect their scores and how to improve them.

The title overall, uses three main themes that go along with my project:

- Personalization: My tool is adapting feedback to each player's strengths and weaknesses, kind of how a real caddy is able to offer advice based on golfer's tendencies.
- AI Empowerment: The tool also uses machine intelligence to analyze and communicate complex patterns in the player data.
- Practical Utility: The tool does not just predict outcomes, it also helps golfers make smarter decisions around the course and helps them develop skills.

Overall, the title of my project reflections the goals and projects main ideas, to make performance analytics more accessible to everyday golfers through an intelligent, conversational based interface.
