---
title: "First reflection post"
date: "2025-11-06"
---


## Reflecting on the Current Version of my Computational Artifact

When looking at the current version of my artifact, it represents a fully functional prototype that is able to bridge data analytics, AI driven feedback, and course strategy recommendation. At this point, the tool integrates many components working together in a cohesive unit:

- SQLite Database:

CaddySense stores golfer profiles locally, allowing for user to enter their name and key stats. This allows the foundation for personalized feedback and long term tracking of their data.

- Data Analyzer:

Using the stored data, the system is able to generate visuals through plots such as histograms, scatter plots, and radar charts. These visuals help identify relationships when it comes to performance metrics.

- AI Coach:

The biggest aspect of the tool so far is the use of local AI model (phi-3) using "Ollama". Users are able to have a conversation with this ,model directly with a personalized "AI coach" and it produces back advice based on their entered stats. The shifts the use from static data tracking to a more dynamic approach in order to have a greater performance improvement guide.

- Course Type Recommendation:

Instead of matching players to specific golf courses, my tool recommends types of course to the golfers based on their profile and their skill metrics. This allows and provides feedback without relying on external API's.

With all of these components, CaddySense functions and shows how AI and data can merge together in order to serve as an intelligent assistant for golfers. It is not yet fully completed, but it lays out a strong foundation and allows for expansion.

Looking at its current state, I am proud of my tool is coming together so far, and I am very excited to further develop it, and make it a much more rounded tool. I will do this by making the tool more refined by adding user progress tracking, and adding more data-driven responses to the recommendations.
